version: "3.9"
services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - ./data/zero:/dgraph
    networks:
      - idea-network
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  alpha:
    image: dgraph/dgraph:latest
    environment:
      - DGRAPH_ALPHA_SECURITY=whitelist=10.0.0.0/8,172.0.0.0/8,192.168.0.0/16;token=password
    volumes:
      - ./data/alpha:/dgraph
    networks:
      - idea-network
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --security whitelist=10.0.0.0/8,172.0.0.0/8,192.168.0.0/16,127.0.0.1

  ratel:
    image: dgraph/ratel:v21.12.0
    ports:
      - published: 8000
        target: 8000
        protocol: tcp
        mode: host
    networks:
      - idea-network
    restart: always

networks:
  idea-network:
    driver: bridge
